### ISSUE TITLE
A grammar mistake

### ISSUE THREAD

**Issue by ascchrvalstr** [Infinicken/Richman4L#1]
`Richman4L is a game which like Richman4Fun.`
Richman4L is a game **like** Richman4Fun.
`like` is a preposition rather than a verb here.

**Comment by riteme** [comment]
Maybe *similar to* is better.

**Comment by WenceyWang** [comment]
I'll fix this in the next commit.

**Comment by WenceyWang** [comment]
貌似杰哥已经全给重写了（（（
（我是文盲不要笑话我了（（
